# PersistentVolume：PV只能是网络存储,不属于任何Node,但Node可以访问
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    # ReadWriteOne|ReadOnlyMany|ReadWriteMany
    - ReadWriteMany
  nfs:
    server: 192.168.201.245
    path: "/apply/banksteelnas"

---

#PersistentVolumeClaim：通过name和PV关联
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
