apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bone-eureka01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bone-eureka01
    spec:
      containers:
        - name: bone-eureka01
          image: 9f.k8s-registry.xxx.local/baseplatform/bone-eureka:v1.9.9
          env:
            - name: AUTHOR
              value: eureka
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bone-eureka01
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: bone-eureka01

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bone-eureka02
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bone-eureka02
    spec:
      containers:
        - name: bone-eureka02
          image: 9f.k8s-registry.xxx.local/baseplatform/bone-eureka:v1.9.9
          env:
            - name: AUTHOR
              value: eureka
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bone-eureka02
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: bone-eureka02
